nodejs https://nodejs.org/dist/v0.12.0/node-v0.12.0.pkg
lastpass https://lastpass.com/download/cdn/lpmacosx.zip
skype http://www.skype.com/en/download-skype/skype-for-mac/downloading/
clipmenu https://dl.dropbox.com/u/1140644/clipmenu/ClipMenu_0.4.3.dmg
sublime https://download.sublimetext.com/Sublime%20Text%20Build%203103.dmg
jdk 7  http://download.oracle.com/otn-pub/java/jdk/7u79-b15/jdk-7u79-macosx-x64.dmg
jdk 8 http://download.oracle.com/otn-pub/java/jdk/8u73-b02/jdk-8u73-macosx-x64.dmg
intellij https://www.jetbrains.com/idea/download/download-thanks.html?platform=mac&code=IIC
slack https://slack.com/ssb/download-osx
virtualbox http://download.virtualbox.org/virtualbox/5.0.14/VirtualBox-5.0.14-105127-OSX.dmg
terraform https://releases.hashicorp.com/terraform/0.6.11/terraform_0.6.11_darwin_amd64.zip
vagrant https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1.dmg
